### ISSUE TITLE
models\sdp.py中的636行左右，x = self.encode(words, feats)，这里encode找不到其方法

### ISSUE THREAD

**Issue by woshuaizuishuai** [LiBinNLP/DynGL-SDP#1]

**Comment by LiBinNLP** [comment]
sorry, only the class DyGLSemanticDependencyModel in models/sdp.py can be instantiated, the other class such as VISemanticDependencyModel or TriaffineSemanticDependencyModel are not be tested, but you can find the correct code in the original repository(https://github.com/yzhangcs/parser).

**Comment by LiBinNLP** [comment]
This repository is an extension of the original repository(https://github.com/yzhangcs/parser). Only the proposed model in this paper is tested, other models that from the original repository are not tested.
